services:
  - type: web
    name: luxury-wedding-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
